# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "uas"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-be6c05b2-15d0-46dd-a1d3-667e9ce68ba9";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-be6c05b2-15d0-46dd-a1d3-667e9ce68ba9".device =
    "/dev/disk/by-uuid/be6c05b2-15d0-46dd-a1d3-667e9ce68ba9";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4328-A821";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-c512f81b-1b63-4a84-b79d-15dbc2c97509"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
